config/routes.rb
Rails.application.routes.draw do

  resources :school_classes
  resources :class_categories
  # School Classes
  # resources :classes
  match "/classes/class-:class_name/", to: "classes#show", via: :get, as: :class_name
  match "/classes/:class_name/edit", to: "classes#edit", via: :get, as: :edit_class
  match "/classes/:class_name/update/", to: "classes#update", via: :patch, as: :update_class
  match "/classes/new/", to: "classes#new", via: :get, as: :new_class
  match "/classes/create/", to: "classes#create", via: :post, as: :create_class
  match "/classes/:class_name/destroy/", to: "classes#destroy", via: :delete, as: :destroy_class
  match "/classes/", to: "classes#index", via: :get, as: :classes
  match "classes/:id/class_details/", to: "classes#class_details", via: :get, as: :class_details
  match "classes/:id/class_details_for_periods/", to: "classes#class_details_for_periods", via: :get, as: :class_details_for_periods
  match "classes/destroy_multiple/", to: "classes#destroy_multiple", via: :delete, as: :destroy_multiple_classes

  resources :classrooms do
    collection do
      delete 'destroy_multiple'
    end
  end


  resources :sessions

  # Fees Criteria
  resources :fees_particulars, only: [:destroy, :edit, :update, :show] do
    collection do
      post "types"
      get "update_students"
    end
  end
  resources :fees_categories do
    collection do
      get "fees_index"
    end
  end
  resources :fees_periods do
    collection do
      get "update_fees_particulars"
    end
  end

  get "home/bootstrap_form_test"

  match 'fees_particulars/new/:id' => 'fees_particulars#new', :via => :get, as: :new_fees_particulars
  match 'fees_particulars/create/:id' => 'fees_particulars#create', :via => :post, as: :create_fees_particulars
  match 'fees_particulars/update/:id' => 'fees_particulars#update', :via => :post, as: :update_fees_particulars
  # get 'home/index'
  root :to => "home#index"

  # match "/settings/" => 'home#settings', :as => :settings

  # Test logs with Redis
  # match "/log/" => 'home#log', :via => [:post]
  # match "/logEvent/" => 'home#log_event', :via => [:post]
  # match "/logException/" => 'home#log_exception', :via => [:post]
  # # match "/events/" => 'home#events', :via => [:get]
  # match "/redis/" => 'home#redis', :via => [:get], :as => :redis


  # Students Criteria
  resources :students do
    collection do
      post "remove_avatar/:id", to: "students#remove_avatar", as: :delete_avatar
      get "admissions"
      delete 'destroy_multiple'
    end
  end
  
  # Subjects Criteria
  resources :subject_allocations do
    collection do
      delete 'destroy_multiple'
      get "update_course"
      get "update_batch"
      get "update_department"
    end
  end
  resources :subjects do
    collection do
      get "update_course"
      get "list"
      delete 'destroy_multiple'
      get "update_course_for_search"
    end
  end
  resources :student_categories

  # Visitors
  # get "visitors/contact_us", to: "visitors#contact_us"
  # get "visitors/about_us", to: "visitors#about_us"
  

  # Employee Attendance
  resources :employee_attendance, only: [:employee_attendance_details] do
    collection do
      get "employee_attendance_details"
    end
  end

  # Employees
  resources :employee_positions
  resources :employees do
    collection do
      post "remove_avatar/:id", to: "employees#remove_avatar", as: :delete_avatar
      get "human_resources"
      delete 'destroy_multiple'
      # get ":employee_position_id/new", to: "employees#teacher_new", as: :new_teacher
      # post ":employee_position_id/create", to: "employees#teacher_create", as: :create_teacher
      get ":id/classes", to: "employees#classes", as: :teacher_class
    end
  end

  # Teachers
  get "/teachers", to: "teachers#index", as: :teachers
  get "/teachers/new", to: "teachers#new", as: :new_teacher
  post "/teachers/create", to: "teachers#create", as: :create_teacher
  get "/teachers/:id/edit", to: "teachers#edit", as: :edit_teacher
  post "/teachers/:id/update", to: "teachers#update", as: :update_teacher
  get "/teachers/:id", to: "teachers#show", as: :teacher
  delete "/teachers/:id/destroy", to: "teachers#destroy", as: :teacher_destroy
  delete "teachers/destroy_multiple/", to: "teachers#destroy_multiple", as: :destroy_multiple_teachers
  post "teacher/:id/remove_avatar", to: "teachers#remove_avatar", as: :delete_avatar_teacher
  # match "/classes/:class_name/edit", to: "classes#edit", via: :get, as: :edit_class
  # match "/classes/:class_name/update/", to: "classes#update", via: :patch, as: :update_class
  # match "/classes/new/", to: "classes#new", via: :get, as: :new_class
  # match "/classes/create/", to: "classes#create", via: :post, as: :create_class
  # match "/classes/:class_name/destroy/", to: "classes#destroy", via: :delete, as: :destroy_class
  # match "/classes/", to: "classes#index", via: :get, as: :classes

  resources :class_teachers, only: [:create, :destroy] do
    collection do
      delete ":id/destroy", to: "class_teachers#destroy", as: :destroy
    end
  end
  resources :classroom_teachers, only: [:create, :destroy] do
    collection do
      delete ":id/destroy", to: "classroom_teachers#destroy", as: :destroy
    end
  end

  # Lessons
  resources :lessons, only: [:destroy] do
    collection do
      match ":school_class_id/lessons", to: "lessons#new", via: :get, as: :new
      match ":school_class_id/create", to: "lessons#create", via: :post, as: :create
    end
  end

  resources :periods do
    collection do
      delete 'destroy_multiple'
    end
  end

  #Timetable
  # resources :time_table do
  #   collection do
  #     get 'view'
  #     get 'allocate_subjects'
  #   end
  # end

  get "/time_table", to: "time_table#index", as: :time_table
  get "/time_table/view", to: "time_table#view"
  get "/time_table/allocate_subjects", to: "time_table#allocate_subjects"
  get "/time_table/pdf/:class_name", to: "time_table#pdf_time_table", as: :pdf_time_table
  post "/time_table/:class_name/update/:period_id", to: "time_table#update", as: :update_time_table
  post "/time_table/:class_name/remove_subject/:period_id", to: "time_table#remove_subject", as: :remove_subject


  # Departments
  resources :departments

  # Courses
  resources :courses do
    collection do
      delete 'destroy_multiple'
    end
  end
  # match "courses/destroy/:id" => "courses#destroy", via: :delete, as: :destroy_course

  # Batches
  resources :batches do
    collection do
      delete 'destroy_multiple'
      get 'update_batches'
    end
  end
  
  # Admissions
  # get "admission" => "admission#index", as: :admissions
  get "/admission/new" => "admission#new", as: :new_admission
  post "/admission" => "admission#create"
  get "/admission/update_course"
  # get "/admission/show/:id" => "admission#show", :as => :admission_detail
  # get "/admission/edit/:id" => "admission#edit", :as => :admission_edit
  # delete "/admission/destroy/:id" => "admission#destroy", :as => :delete_admission
  # post "/admission/update/:id" => "admission#update", as: :update_admission

  # routes for school information
  get "general/settings", as: :school_edit
  match '/general/settings/update', to: 'school#update', :via => :post, as: :school_update

  ActiveAdmin.routes(self)
  # authenticated :user do
  #   root :to => "home#index"
  # end
  # unauthenticated :user do
  #   devise_scope :user do 
  #     get "/" => "devise/sessions#new"
  #   end
  # end

  devise_scope :user do
    match '/sessions/user', to: 'devise/sessions#create', via: :post
  end
  devise_for :users, :controllers => { :registrations => "registrations" } 
  resources :users
end


# For Production Enviroment
# if Rails.env.production?
#   devise_for :users, :controllers => { :registrations => "registrations" } 
# else
#   devise_for :users
# end

app/models/employee.rb
# == Schema Information
#
# Table name: employees
#
#  id                   :integer          not null, primary key
#  first_name           :string(255)
#  last_name            :string(255)
#  date_of_birth        :date(255)
#  gender               :string(255)
#  employee_number      :string(255)
#  joining_date         :date
#  department_id        :integer
#  employee_position_id :integer
#  job_title            :string(255)
#  qualification        :string(255)
#  total_experience     :string(255)
#  present_address      :text
#  perminent_address    :text
#  phone                :string(255)
#  email                :string(255)
#  created_at           :datetime
#  updated_at           :datetime
#  avatar_file_name     :string(255)
#  avatar_content_type  :string(255)
#  avatar_file_size     :integer
#  avatar_updated_at    :datetime
#

class Employee < ActiveRecord::Base
  belongs_to :department
  belongs_to :employee_position 

  # has_many :classroom_teachers, :foreign_key => :teacher_id
  # has_many :classrooms, :through => :classroom_teachers

  # has_many :class_teachers, :foreign_key => :teacher_id
  # has_many :school_classes, :through => :class_teachers

  has_many :lessons, :foreign_key => :teacher_id
  has_many :school_classes, :through => :lessons

  has_many :classrooms, :through => :lessons

  # has_many :lessons, :foreign_key => :teacher_id
  has_many :subjects, :through => :lessons

  # has_many :lessons, :foreign_key => :teacher_id
  has_many :periods, :through => :lessons

  # has_many :periods

  has_many :educations, :foreign_key => :teacher_id, dependent: :destroy

  has_many :experiences, :foreign_key => :teacher_id, dependent: :destroy
  accepts_nested_attributes_for :experiences, :allow_destroy => true
  accepts_nested_attributes_for :educations, :allow_destroy => true
  # , reject_if: lamda {|a| a["institute_name"].blank?}
  # , reject_if: lamda {|a| a["company"].blank?}

  scope :teachers , -> { joins(:employee_position).where(employee_positions: {:name => "Teacher"}) }

  # validations
  validates_presence_of :employee_number,:first_name,:last_name,
                        :job_title, :employee_position_id, :email, :phone, :date_of_birth,
                        :joining_date, :present_address,
                        :gender

  # File Upload
  has_attached_file :avatar, :styles => { :medium => "200x200>", :thumb => "100x100>"}, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
  attr_accessor :remove_avatar

  GENDER = ["Male", "Female"]

  def to_s
    "#{first_name} #{last_name}"
  end

  def check_attendence?(dated)
    if self.employee_attendences.present?
      emp = self.employee_attendences.last
      if emp.date < dated.to_date || emp.date > dated.to_date
        "x"
      else
        if emp.Absent?
          "A"
        else
          "P"
        end
      end
    else
      "x"
    end
  end

  def self.teachers_position(*args)
    if args.size == 0 
      position = EmployeePosition.find_by_name("Teacher")
      teacher = position.employees.build    
    else  
      if args.size == 1  
        position = EmployeePosition.find_by_name("Teacher")
        teacher = position.employees.build(args.first)
        teacher.save
      end  
    end      
  end
end

app/controllers/employees_controller.rb
class EmployeesController < InheritedResources::Base
  before_filter :authenticate_user!
  before_filter :set_employee_id, only: [:show, :edit, :update, :destroy, :remove_avatar]
  def human_resources
    add_breadcrumb "Human Resources"
  end

  def index
    @teacher_position = EmployeePosition.find_by_name("Teacher")
    @employees = Employee.all
    add_breadcrumb "Human Resources", human_resources_employees_path
    add_breadcrumb "Employees"
  end

  def new
    @employee = Employee.new
    add_breadcrumb "Human Resources", human_resources_employees_path
    add_breadcrumb "Employees", employees_path
    add_breadcrumb "New Employee"
  end

  def teacher_new
    add_breadcrumb "Human Resources", human_resources_employees_path
    add_breadcrumb "Employees", employees_path
    add_breadcrumb "New Teacher"
    @teacher = Employee.new
    @teacher_position = EmployeePosition.find_by_name("Teacher")
  end


  def classes
    add_breadcrumb "Human Resources", human_resources_employees_path
    add_breadcrumb "Employees", employees_path
    add_breadcrumb "Classes"
    @teacher = Employee.find(params[:id])
    @classes = SchoolClass.all
    @classrooms = Classroom.all
  end

  def edit
    add_breadcrumb "Human Resources", human_resources_employees_path
    add_breadcrumb "Employees", employees_path
    add_breadcrumb "Edit Employee Informations"
  end

  def show
    add_breadcrumb "Human Resources", human_resources_employees_path
    add_breadcrumb "Employees", employees_path
    add_breadcrumb "Details"
    @teacher = Employee.find(params[:id])
  end


  def teacher_create
    add_breadcrumb "Human Resources", human_resources_employees_path
    add_breadcrumb "Employees", employees_path
    add_breadcrumb "New Teacher"
    @teacher_position = EmployeePosition.find_by_name("Teacher")
    @teacher = @teacher_position.employees.build(employees_params)
    if @teacher.save
      flash[:notice] = "Teacher Created Successfully"
      if SchoolClass.exists?(1) || Classroom.exists?(1)
        redirect_to teacher_class_employees_path(@teacher)
      else
        redirect_to @teacher
      end
    else
      flash[:notice] = @employee.errors.full_messages.to_sentence
      render action: 'teacher_new'
    end
  end

  def create
    add_breadcrumb "Human Resources", human_resources_employees_path
    add_breadcrumb "Employees", employees_path
    add_breadcrumb "New Employee"
    @employee = Employee.new(employees_params)
    # if @employee.save
    #   redirect_to @employee
    #   flash[:notice] = "Employee Created Successfully"

    # else
    #   redirect_to :back
    #   flash[:alert] = @employee.errors.full_messages.to_sentence
    # end
    respond_to do |format|
       if @employee.save
         format.html { redirect_to @employee, notice: 'Employee Created Successfully' }
         format.json { render action: 'show', status: :created, location: @employee }
         format.json { render json: @employee }
       else
         format.html { render action: 'new' }
         flash[:alert] = @employee.errors.full_messages.to_sentence
         format.json { render json: @employee.errors, status: :unprocessable_entity }
         format.json { render json: @employee.errors.full_messages, status: :unprocessable_entity }
       end
     end
  end

  def update
    add_breadcrumb "Human Resources", human_resources_employees_path
    add_breadcrumb "Employees", employees_path
    add_breadcrumb "Edit Employee Informations"
    # @employee.update_attributes(employees_params)
    # if @employee.save
    #   redirect_to @employee
    #   flash[:notice] = "Employee Updated Successfully"
    # else
    #   redirect_to :back
    #   flash[:alert] = @employee.errors.full_messages.to_sentence
    # end
    respond_to do |format|
       if @employee.update(employees_params)
         format.html { redirect_to @employee, notice: 'Employee Updated Successfully' }
         format.json { head :no_content }
         format.json { render json: @employee }
       else
         format.html { render action: 'edit' }
         flash[:alert] = @employee.errors.full_messages.to_sentence
         format.json { render json: @employee.errors, status: :unprocessable_entity }
         format.json { render json: @employee.errors.full_messages, status: :unprocessable_entity }
       end
     end
  end

  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_path }
      flash[:alert] = "Employee Destroyed"
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end

  def remove_avatar
    @employee.avatar = nil
    @employee.save
    redirect_to employee_path(@employee)
  end

  def destroy_multiple
    Employee.destroy(params[:employee_destroy_id])
    flash[:notice] = "Employees were successfully destroyed."
    respond_to do |format|
      format.html { redirect_to employees_path }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end
  
  private

  def set_employee_id
    begin
      @employee = Employee.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to employes_url, :flash => { :error => "Request Page not found." }
    end
  end

  def employees_params
    params.require(:employee).permit(:first_name, :last_name, :date_of_birth, :gender, :employee_number,
                                     :joining_date, :job_title, :qualification, :total_experience, :present_address,
                                     :perminent_address, :phone, :email, :department_id, :avatar, :employee_position_id)
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
  def attendence_label(value)
    if value.employee_attendences.first.label == 0
      "Present"
    elsif value.employee_attendences.first.label == 1
      "Absent"
    else
      "Blank"
    end
  end
  
end

app/views/employees/_employee_picture.html.erb
<div class="form-group"></div>
  
<% if @employee.present? %>
  <div class="fileinput fileinput-new" data-provides="fileinput">
    <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
      <% unless @employee.avatar.present? %>
        <%= image_tag("school.png") %>
      <% else %>
        <%= image_tag @employee.avatar.url %>
      <% end %>
    </div>
    <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>
    <div>
      <span class="btn btn-default btn-file"><span class="fileinput-new">Select image</span><span class="fileinput-exists">Change</span><%= file_field(:employee, :avatar) %></span>
      <% unless @employee.avatar.present? %>
        <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
      <% else %>
        <% if file_field nil, :class => "fileinput-exists" %>
          <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
        <% end %>
        <%= link_to "Remove Picture", delete_avatar_employees_path, :method => :post, class: "btn btn-default", data: {confirm: "Are you sure?"} %>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="fileinput fileinput-new" data-provides="fileinput">
    <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
      <!-- <img data-src="holder.js/100%x100%" alt="..."> -->
      <%= image_tag("school.png") %>
    </div>
    <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>
    <div>
      <span class="btn btn-default btn-file"><span class="fileinput-new">Select image</span><span class="fileinput-exists">Change</span>
        <%= file_field(:employee, :avatar) %>
      </span>
      <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
    </div>
  </div>
<% end %>

app/views/employees/_form.html.erb
<%= bootstrap_form_for @employee, label_errors: true, class: "form-horizontal", :html => {:multipart => true} do |f| %>
  <%#= f.error_notification %>
  <div class="row">
    <div class="col-sm-6">
      <h3>Bio:</h3>
      <fieldset>
        <div class="form-inputs">
          <%= f.text_field :first_name, input_html: {class: "form-control"}, autofocus: true, placeholder: "First Name" %>
        </div>


        <div class="form-inputs">
          <%= f.text_field :last_name, input_html: {class: "form-control"}, placeholder: "Last Name" %>
        </div>

        <div class="form-inputs">
          <%= f.text_field :date_of_birth, class: "form-control", :data => {'date-format' => 'YYYY/MM/DD'}, as: :string, :placeholder => "Date of birth" %>
        </div>

        <div class="form-inputs">
          <%= f.select :gender, Employee::GENDER, input_html: {class: "form-control"}, prompt: "Choose your Gender" %>
        </div>
      </fieldset>

      <h3>Address:</h3>
      <fieldset>
        <div class="form-inputs">
          <%= f.text_area :present_address, input_html: {class: "form-control"}, placeholder: "Current Address" %>
        </div>

        <div class="form-inputs">
          <%= f.text_area :perminent_address, input_html: {class: "form-control"}, placeholder: "Permenent Address" %>
        </div>

        <div class="form-inputs">
          <%=  f.phone_field :phone, input_html: {class: "form-control"}, placeholder: "Contact Number" %>
        </div>

        <div class="form-inputs">
          <%= f.email_field :email, input_html: {class: "form-control"}, placeholder: "Email Address" %>
        </div>
      </fieldset>
    </div>
    <div class="col-sm-6">
      <h3>Employee Information:</h3>
      <fieldset>
        <div class="form-inputs">
          <%= f.number_field :employee_number, input_html: {class: "form-control"}, placeholder: "Employee Number" %>
        </div>

        <div class="form-inputs">
          <%#= f.label :joining_date, required: true %>
          <%= f.text_field :joining_date, class: "form-control", :data => {'date-format' => 'YYYY/MM/DD'}, as: :string, :placeholder => "Joining Date" %>
        </div>
        <div class="form-inputs">
          <%= f.select :employee_position_id, EmployeePosition.all.map{|m| [m.name, m.id]}, class: "form-control", autofocus: true, prompt: "Choose an Employee Position" %>
        </div>
        <div class="form-inputs">
          <%= f.select :department_id, Department.all.map{|m| [m.name, m.id]}, class: "form-control", autofocus: true, prompt: "Choose a Department" %>
        </div>
        <div class="form-inputs">
          <%= f.text_field :job_title, input_html: {class: "form-control"}, placeholder: "Job Title" %>
        </div>
      </fieldset>

      <h3>Qualification and Experience:</h3>
      <fieldset>
        <div class="form-inputs">
          <%= f.text_field :qualification, input_html: {class: "form-control"}, placeholder: "Qualification" %>
        </div>
        <div class="form-group"></div>
        <div class="form-inputs">
          <%= f.text_field :total_experience, input_html: {class: "form-control"}, placeholder: "Total Experience", label: false %>
        </div>
      </fieldset>
      <h3>Profile Picture</h3>
      <%= render :partial => 'employee_picture', locals: {:f => f} %>
    </div>
  </div>
        
  <div class="form-group"></div>

  <div class="form-actions">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
  
<% end %>

app/views/employees/destroy.js.erb
$('.delete_employee').bind('ajax:success', function() {  
    $(this).closest('tr').fadeOut();
    $("#notice").html("<%= escape_javascript(render :partial => 'layouts/messages' , :locals => { :flash => flash }).html_safe %>")
}); 

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>
<hr />
<%= render 'form' %>

app/views/employees/human_resources.html.erb
<div class="col-md-2 dashboard-width">
  <div class="employees dashboard-icon">
    <%= link_to image_tag("employees2.png"), human_resources_employees_path %>
    <br />
    Human Resources
  </div>
</div>
<div class="col-md-9">
	<ul>
		<li>
			
			<h1>
				<%= link_to "Employees", employees_path %>
			</h1>
			
		</li>
		<li>
			
			<h1>
				<%= link_to "Employee Positions", employee_positions_path %>
			</h1>
			
		</li>
		<li>
			
			<h1>
				<%= link_to "Employee Attendances", employee_attendance_details_employee_attendance_index_path %>
			</h1>
			
		</li>
	</ul>
</div>

app/views/employees/index.html.erb
<h1>Employees</h1>

<%= form_tag destroy_multiple_employees_path, method: :delete do %>
  <div class="row">
    <div class="col-sm-12">
      <div class="pull-left">
        <%= link_to 'New Employee', new_employee_path, class: "btn btn-success" %>
        <%#= link_to 'New Teacher', new_teacher_employees_path(@teacher_position.name), class: "btn btn-success", data: { no_turbolink: true } %>
      </div>
      <div class="pull-right">
        <%= button_tag "Delete selected", :remote => true, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-sm destroy-all pull-right", id: "my" %><br />
        <span id="select_notice" style="font-size:13px;" class="pull-right"></span>
      </div>
    </div>
  </div>
  <hr />
  <div class="row">
    <div class="col-sm-12">
      <div class="table-responsive">
        <table id="employees_datatable" class= "table table-striped ">
          <thead >
            <tr>
              <th>Mark All <input type="checkbox" id="select_all"/></th>
              <th>Name</th>
              <th>Gender</th>
              <th>Department</th>
              <th>Position</th>
              <th>Job title</th>
              <th>Actions</th>
            </tr>
          </thead>

          <tbody>
            <% @employees.each do |employee| %>
              <tr>
                <td class="selectedId"><%= check_box_tag "employee_destroy_id[]", employee.id %></td>
                <td><%= employee.first_name %></td>
                <td><%= employee.gender %></td>
                <td><%= employee.department.name  unless employee.department.nil? %></td>
                <td><%= employee.employee_position.name  unless employee.employee_position.nil? %></td>
                <td><%= employee.job_title %></td>
                <td class="dataTable_actions">
                  <%= link_to 'Details', employee, class: "label label-info" %>
                  <%= link_to 'Edit', edit_employee_path(employee), class: "label label-primary" %>
                  <%= link_to 'Destroy', employee, method: :delete, remote: true, data: { confirm: 'Are you sure?' }, class: "label label-danger delete_employee" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
<% end %>
<div class="row">&nbsp;</div>


<br>

app/views/employees/new.html.erb
<h1>Create Employee</h1>
<hr />
<%= render 'form' %>

app/views/employees/show.html.erb
<div class="panel panel-app">
  <div class="panel-heading">
    <h1>Employee Detail</h1>
    <%= link_to 'Edit', edit_employee_path(@employee), class: "label label-info" %> |
    <%= link_to 'Back', employees_path, class: "label label-default" %>
  </div>
  <div class="panel-body">
    <div class="fileinput fileinput-new" data-provides="fileinput">
      <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
        <% unless @employee.avatar.present? %>
          <%= image_tag("school.png") %>
        <% else %>
          <%= image_tag @employee.avatar.url %>
        <% end %>
      </div>
      <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>
    </div>
    <%= link_to "Add Class", teacher_class_employees_path(@teacher), class: "btn btn-success pull-right" if @teacher.employee_position.name == "Teacher" %>
    <table class="table table-bordered table-hover">
      <tr>
        <td><strong>First name:</strong></td>
        <td><%= @employee.first_name %></td>
      </td>
      <tr>
        <td><strong>Last name:</strong></td>
        <td><%= @employee.last_name %></td>
      </tr>
        <td><strong>Date of birth:</strong></td>
        <td><%= @employee.date_of_birth unless @employee.date_of_birth.nil? %></td>
      </tr>
      <tr>
        <td><strong>Gender:</strong></td>
        <td><%= @employee.gender %></td>
      </tr>
      <tr>
        <td><strong>Employee number:</strong></td>
        <td><%= @employee.employee_number %></td>
      </tr>
      <tr>
        <td><strong>Joining date:</strong></td>
        <td><%= @employee.joining_date.strftime("%d/%b/%Y") %></td>
      </tr>
      <tr>
        <td><strong>Department:</strong></td>
        <td><%= @employee.department.name unless @employee.department.nil? %></td>
      </tr>
      <tr>
        <td><strong>Employee position:</strong></td>
        <td><%= @employee.employee_position.name unless @employee.employee_position.nil? %></td>
      </tr>
      <tr>
        <td><strong>Job title:</strong></td>
        <td><%= @employee.job_title %></td>
      </tr>
      <tr>
        <td><strong>Qualification:</strong></td>
        <td><%= @employee.qualification %></td>
      </tr>
      <tr>
        <td><strong>Total experience:</strong></td>
        <td><%= @employee.total_experience %></td>
      </tr>
      <tr>
        <td><strong>Present address:</strong></td>
        <td><%= @employee.present_address %></td>
      </tr>
      <tr>
        <td><strong>Perminent address:</strong></td>
        <td><%= @employee.perminent_address %></td>
      </tr>
      <tr>
        <td><strong>Phone:</strong></td>
        <td><%= @employee.phone %></td>
      </tr>
      <tr>
        <td><strong>Email:</strong></td>
        <td><%= @employee.email %></td>
      </tr>
    </table>
  </div>
</div>
 