config/routes.rb
Rails.application.routes.draw do

  resources :school_classes
  resources :class_categories
  # School Classes
  # resources :classes
  match "/classes/class-:class_name/", to: "classes#show", via: :get, as: :class_name
  match "/classes/:class_name/edit", to: "classes#edit", via: :get, as: :edit_class
  match "/classes/:class_name/update/", to: "classes#update", via: :patch, as: :update_class
  match "/classes/new/", to: "classes#new", via: :get, as: :new_class
  match "/classes/create/", to: "classes#create", via: :post, as: :create_class
  match "/classes/:class_name/destroy/", to: "classes#destroy", via: :delete, as: :destroy_class
  match "/classes/", to: "classes#index", via: :get, as: :classes
  match "classes/:id/class_details/", to: "classes#class_details", via: :get, as: :class_details
  match "classes/:id/class_details_for_periods/", to: "classes#class_details_for_periods", via: :get, as: :class_details_for_periods
  match "classes/destroy_multiple/", to: "classes#destroy_multiple", via: :delete, as: :destroy_multiple_classes

  resources :classrooms do
    collection do
      delete 'destroy_multiple'
    end
  end


  resources :sessions

  # Fees Criteria
  resources :fees_particulars, only: [:destroy, :edit, :update, :show] do
    collection do
      post "types"
      get "update_students"
    end
  end
  resources :fees_categories do
    collection do
      get "fees_index"
    end
  end
  resources :fees_periods do
    collection do
      get "update_fees_particulars"
    end
  end

  get "home/bootstrap_form_test"

  match 'fees_particulars/new/:id' => 'fees_particulars#new', :via => :get, as: :new_fees_particulars
  match 'fees_particulars/create/:id' => 'fees_particulars#create', :via => :post, as: :create_fees_particulars
  match 'fees_particulars/update/:id' => 'fees_particulars#update', :via => :post, as: :update_fees_particulars
  # get 'home/index'
  root :to => "home#index"

  # match "/settings/" => 'home#settings', :as => :settings

  # Test logs with Redis
  # match "/log/" => 'home#log', :via => [:post]
  # match "/logEvent/" => 'home#log_event', :via => [:post]
  # match "/logException/" => 'home#log_exception', :via => [:post]
  # # match "/events/" => 'home#events', :via => [:get]
  # match "/redis/" => 'home#redis', :via => [:get], :as => :redis


  # Students Criteria
  resources :students do
    collection do
      post "remove_avatar/:id", to: "students#remove_avatar", as: :delete_avatar
      get "admissions"
      delete 'destroy_multiple'
    end
  end
  
  # Subjects Criteria
  resources :subject_allocations do
    collection do
      delete 'destroy_multiple'
      get "update_course"
      get "update_batch"
      get "update_department"
    end
  end
  resources :subjects do
    collection do
      get "update_course"
      get "list"
      delete 'destroy_multiple'
      get "update_course_for_search"
    end
  end
  resources :student_categories

  # Visitors
  # get "visitors/contact_us", to: "visitors#contact_us"
  # get "visitors/about_us", to: "visitors#about_us"
  

  # Employee Attendance
  resources :employee_attendance, only: [:employee_attendance_details] do
    collection do
      get "employee_attendance_details"
    end
  end

  # Employees
  resources :employee_positions
  resources :employees do
    collection do
      post "remove_avatar/:id", to: "employees#remove_avatar", as: :delete_avatar
      get "human_resources"
      delete 'destroy_multiple'
      # get ":employee_position_id/new", to: "employees#teacher_new", as: :new_teacher
      # post ":employee_position_id/create", to: "employees#teacher_create", as: :create_teacher
      get ":id/classes", to: "employees#classes", as: :teacher_class
    end
  end

  # Teachers
  get "/teachers", to: "teachers#index", as: :teachers
  get "/teachers/new", to: "teachers#new", as: :new_teacher
  post "/teachers/create", to: "teachers#create", as: :create_teacher
  get "/teachers/:id/edit", to: "teachers#edit", as: :edit_teacher
  post "/teachers/:id/update", to: "teachers#update", as: :update_teacher
  get "/teachers/:id", to: "teachers#show", as: :teacher
  delete "/teachers/:id/destroy", to: "teachers#destroy", as: :teacher_destroy
  delete "teachers/destroy_multiple/", to: "teachers#destroy_multiple", as: :destroy_multiple_teachers
  post "teacher/:id/remove_avatar", to: "teachers#remove_avatar", as: :delete_avatar_teacher
  # match "/classes/:class_name/edit", to: "classes#edit", via: :get, as: :edit_class
  # match "/classes/:class_name/update/", to: "classes#update", via: :patch, as: :update_class
  # match "/classes/new/", to: "classes#new", via: :get, as: :new_class
  # match "/classes/create/", to: "classes#create", via: :post, as: :create_class
  # match "/classes/:class_name/destroy/", to: "classes#destroy", via: :delete, as: :destroy_class
  # match "/classes/", to: "classes#index", via: :get, as: :classes

  resources :class_teachers, only: [:create, :destroy] do
    collection do
      delete ":id/destroy", to: "class_teachers#destroy", as: :destroy
    end
  end
  resources :classroom_teachers, only: [:create, :destroy] do
    collection do
      delete ":id/destroy", to: "classroom_teachers#destroy", as: :destroy
    end
  end

  # Lessons
  resources :lessons, only: [:destroy] do
    collection do
      match ":school_class_id/lessons", to: "lessons#new", via: :get, as: :new
      match ":school_class_id/create", to: "lessons#create", via: :post, as: :create
    end
  end

  resources :periods do
    collection do
      delete 'destroy_multiple'
    end
  end

  #Timetable
  # resources :time_table do
  #   collection do
  #     get 'view'
  #     get 'allocate_subjects'
  #   end
  # end

  get "/time_table", to: "time_table#index", as: :time_table
  get "/time_table/view", to: "time_table#view"
  get "/time_table/allocate_subjects", to: "time_table#allocate_subjects"
  get "/time_table/pdf/:class_name", to: "time_table#pdf_time_table", as: :pdf_time_table
  post "/time_table/:class_name/update/:period_id", to: "time_table#update", as: :update_time_table
  post "/time_table/:class_name/remove_subject/:period_id", to: "time_table#remove_subject", as: :remove_subject


  # Departments
  resources :departments

  # Courses
  resources :courses do
    collection do
      delete 'destroy_multiple'
    end
  end
  # match "courses/destroy/:id" => "courses#destroy", via: :delete, as: :destroy_course

  # Batches
  resources :batches do
    collection do
      delete 'destroy_multiple'
      get 'update_batches'
    end
  end
  
  # Admissions
  # get "admission" => "admission#index", as: :admissions
  get "/admission/new" => "admission#new", as: :new_admission
  post "/admission" => "admission#create"
  get "/admission/update_course"
  # get "/admission/show/:id" => "admission#show", :as => :admission_detail
  # get "/admission/edit/:id" => "admission#edit", :as => :admission_edit
  # delete "/admission/destroy/:id" => "admission#destroy", :as => :delete_admission
  # post "/admission/update/:id" => "admission#update", as: :update_admission

  # routes for school information
  get "general/settings", as: :school_edit
  match '/general/settings/update', to: 'school#update', :via => :post, as: :school_update

  ActiveAdmin.routes(self)
  # authenticated :user do
  #   root :to => "home#index"
  # end
  # unauthenticated :user do
  #   devise_scope :user do 
  #     get "/" => "devise/sessions#new"
  #   end
  # end

  devise_scope :user do
    match '/sessions/user', to: 'devise/sessions#create', via: :post
  end
  devise_for :users, :controllers => { :registrations => "registrations" } 
  resources :users
end


# For Production Enviroment
# if Rails.env.production?
#   devise_for :users, :controllers => { :registrations => "registrations" } 
# else
#   devise_for :users
# end

app/models/fees_category.rb
# == Schema Information
#
# Table name: fees_categories
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#

class FeesCategory < ActiveRecord::Base
  has_many :fees_particulars, dependent: :destroy
  has_many :fees_periods
  
  def to_s
    name
  end

  def self.find_or_create(attributes)
    FeesCategory.where(attributes).first || FeesCategory.create(attributes)
  end
end

app/controllers/fees_categories_controller.rb
class FeesCategoriesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :set_fees_category_id, only: [:show, :edit, :update, :destroy, :fees_particulars,
                                              :create_fees_particulars]
  
  def fees_index
    add_breadcrumb "Fees"
  end

  def index
    @fees_categories = FeesCategory.all
    add_breadcrumb "Fees", fees_index_fees_categories_path
    add_breadcrumb "Fees Categories"
  end

  def new
    @fees_category = FeesCategory.new

    add_breadcrumb "Fees", fees_index_fees_categories_path
    add_breadcrumb "Fees Categories", fees_categories_path
    add_breadcrumb "New Fees Category"
  end

  def fees_particulars
    @fees_category.fees_particulars.build
  end

  def create_fees_particulars
    @fees_category.fees_particulars.build(fees_particulars_params)
    if @fees_particular
      redirect_to fees_categories_path, notice: "Particular Added"
    else
      reder :fees_particulars
    end
  end

  def edit
    add_breadcrumb "Fees", fees_index_fees_categories_path
    add_breadcrumb "Fees Categories", fees_categories_path
    add_breadcrumb "Edit Fees Category"
  end

  def show
    add_breadcrumb "Fees", fees_index_fees_categories_path
    add_breadcrumb "Fees Categories", fees_categories_path
    add_breadcrumb "Details"
  end

  def create
    @fees_category = FeesCategory.new(fees_categories_params)
    if @fees_category.save
      redirect_to fees_categories_path, notice: "Fees Category Added"
    else
      render :new
    end
  end

  def update
    if @fees_category.update_attributes(fees_categories_params)
      redirect_to fees_categories_path, notice: "Fees Category Updated"
    else
      render :edit
    end
  end

  def destroy
    @fees_category.destroy
    redirect_to :back
  end

  private

    def fees_categories_params
      params.require(:fees_category).permit(:name, :description)
    end

    def fees_particulars_params
      params.require(:fees_particular).permit(:name, :description, :fees_category_id, :all, :roll_no, :batch_id, :amount)
    end

    def set_fees_category_id
      begin
         @fees_category = FeesCategory.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        redirect_to fees_categories_url, :flash => { :error => "Request Page not found." }
      end
    end
end

app/helpers/fees_categories_helper.rb
module FeesCategoriesHelper
end

app/views/fees_categories/_form.html.erb
<fieldset>
  <%= simple_form_for @fees_category, class: "form-horizontal" do |f| %>
    <%= yield f %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :name, input_html: {class: "form-control"}, autofocus: true, placeholder: "Category Name" %>
    </div>

    <div class="form-group"></div>

    <div class="form-inputs">
      <%= f.input :description, input_html: {class: "form-control"}, placeholder: "Description" %>

    <div class="form-group"></div>

    <div class="form-actions">
      <%= f.button :submit, class: "btn btn-primary" %>
    </div>
    
    <div class="form-group"></div>
  <% end %>
</fieldset>

app/views/fees_categories/edit.html.erb
<%= render :layout => 'form' do |f| %>
  <legend><h1>Edit Fees Category</h1></legend>
<% end %>
<%= link_to 'Back', fees_categories_path %>

app/views/fees_categories/fees_index.html.erb
<div class="col-md-2 dashboard-width">
    <div class="fees dashboard-icon">
      <%= link_to image_tag("fees.png"), {:action => 'fees_index', :controller => 'fees_categories'} %>
      <br />
      Fees
    </div>
</div>

<ul>
	<li>
		<h1>
			<%= link_to "Fees Category", fees_categories_path %>
		</h1>
	</li>
	<li>
		<h1>
			<%= link_to "Fees Period", fees_periods_path %>
		</h1>
	</li>
</ul>

app/views/fees_categories/fees_particulars.html.erb
<%= render partial: "fees_particulars/new" %>

app/views/fees_categories/index.html.erb
<h1>Fees Categories</h1>

<%= link_to 'New Category', new_fees_category_path, class: "btn btn-success" %>
<div class="row">&nbsp;</div>
<div class="row">
  <div class="col-sm-12">
    <div class="table-responsive">
      <table class= "table table-striped table-bordered table-hover ">
        <thead >
          <tr>
            <th class="col-sm-2">Name</th>
            <th>Description</th>
            <th>Particular</th>
            <th colspan="3" align="center">Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @fees_categories.each do |fees_category| %>
            <tr>
              <td><%= fees_category.name %></td>
              <td><%= fees_category.description %></td>
              <%= hidden_field_tag :fees_category_id, fees_category.id %>
              <td><%= link_to 'Add<br />Particular'.html_safe, new_fees_particulars_path(fees_category), class: "btn btn-link", locals: {:fees_category => fees_category} %></td>
              <td><%= link_to 'View Details', fees_category, class: "btn btn-link" %></td>
              <td><%= link_to 'Edit', edit_fees_category_path(fees_category), class: "btn btn-link" %></td>
              <td><%= link_to 'Destroy', fees_category, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/fees_categories/new.html.erb
<%= render :layout => 'form' do |f| %>
  <legend><h1>Create a Fees Category</h1></legend>
<% end %>
<%= link_to 'Back', fees_categories_path %>

app/views/fees_categories/show.html.erb
<div class="panel panel-app">
  <div class="panel-heading">
    <h1>Fees Category Details</h1>
  </div>
  <div class="panel-body">
    <table class="table table-bordered table-hover">
      <tr>
        <td><strong>Name: </strong></td>
        <td><%= @fees_category.name %></td>
      </td>
      <tr>
        <td><strong>Description: </strong></td>
        <td><%= @fees_category.description %></td>
      </tr>
    </table>
  </div>
</div>
 
<%= link_to 'Edit', edit_fees_category_path(@fees_category), class: "btn btn-link" %> |
<%= link_to 'Back', fees_categories_path, class: "btn btn-link" %>