config/routes.rb
Rails.application.routes.draw do

  resources :school_classes
  resources :class_categories
  # School Classes
  # resources :classes
  match "/classes/class-:class_name/", to: "classes#show", via: :get, as: :class_name
  match "/classes/:class_name/edit", to: "classes#edit", via: :get, as: :edit_class
  match "/classes/:class_name/update/", to: "classes#update", via: :patch, as: :update_class
  match "/classes/new/", to: "classes#new", via: :get, as: :new_class
  match "/classes/create/", to: "classes#create", via: :post, as: :create_class
  match "/classes/:class_name/destroy/", to: "classes#destroy", via: :delete, as: :destroy_class
  match "/classes/", to: "classes#index", via: :get, as: :classes
  match "classes/:id/class_details/", to: "classes#class_details", via: :get, as: :class_details
  match "classes/:id/class_details_for_periods/", to: "classes#class_details_for_periods", via: :get, as: :class_details_for_periods
  match "classes/destroy_multiple/", to: "classes#destroy_multiple", via: :delete, as: :destroy_multiple_classes

  resources :classrooms do
    collection do
      delete 'destroy_multiple'
    end
  end


  resources :sessions

  # Fees Criteria
  resources :fees_particulars, only: [:destroy, :edit, :update, :show] do
    collection do
      post "types"
      get "update_students"
    end
  end
  resources :fees_categories do
    collection do
      get "fees_index"
    end
  end
  resources :fees_periods do
    collection do
      get "update_fees_particulars"
    end
  end

  get "home/bootstrap_form_test"

  match 'fees_particulars/new/:id' => 'fees_particulars#new', :via => :get, as: :new_fees_particulars
  match 'fees_particulars/create/:id' => 'fees_particulars#create', :via => :post, as: :create_fees_particulars
  match 'fees_particulars/update/:id' => 'fees_particulars#update', :via => :post, as: :update_fees_particulars
  # get 'home/index'
  root :to => "home#index"

  # match "/settings/" => 'home#settings', :as => :settings

  # Test logs with Redis
  # match "/log/" => 'home#log', :via => [:post]
  # match "/logEvent/" => 'home#log_event', :via => [:post]
  # match "/logException/" => 'home#log_exception', :via => [:post]
  # # match "/events/" => 'home#events', :via => [:get]
  # match "/redis/" => 'home#redis', :via => [:get], :as => :redis


  # Students Criteria
  resources :students do
    collection do
      post "remove_avatar/:id", to: "students#remove_avatar", as: :delete_avatar
      get "admissions"
      delete 'destroy_multiple'
    end
  end
  
  # Subjects Criteria
  resources :subject_allocations do
    collection do
      delete 'destroy_multiple'
      get "update_course"
      get "update_batch"
      get "update_department"
    end
  end
  resources :subjects do
    collection do
      get "update_course"
      get "list"
      delete 'destroy_multiple'
      get "update_course_for_search"
    end
  end
  resources :student_categories

  # Visitors
  # get "visitors/contact_us", to: "visitors#contact_us"
  # get "visitors/about_us", to: "visitors#about_us"
  

  # Employee Attendance
  resources :employee_attendance, only: [:employee_attendance_details] do
    collection do
      get "employee_attendance_details"
    end
  end

  # Employees
  resources :employee_positions
  resources :employees do
    collection do
      post "remove_avatar/:id", to: "employees#remove_avatar", as: :delete_avatar
      get "human_resources"
      delete 'destroy_multiple'
      # get ":employee_position_id/new", to: "employees#teacher_new", as: :new_teacher
      # post ":employee_position_id/create", to: "employees#teacher_create", as: :create_teacher
      get ":id/classes", to: "employees#classes", as: :teacher_class
    end
  end

  # Teachers
  get "/teachers", to: "teachers#index", as: :teachers
  get "/teachers/new", to: "teachers#new", as: :new_teacher
  post "/teachers/create", to: "teachers#create", as: :create_teacher
  get "/teachers/:id/edit", to: "teachers#edit", as: :edit_teacher
  post "/teachers/:id/update", to: "teachers#update", as: :update_teacher
  get "/teachers/:id", to: "teachers#show", as: :teacher
  delete "/teachers/:id/destroy", to: "teachers#destroy", as: :teacher_destroy
  delete "teachers/destroy_multiple/", to: "teachers#destroy_multiple", as: :destroy_multiple_teachers
  post "teacher/:id/remove_avatar", to: "teachers#remove_avatar", as: :delete_avatar_teacher
  # match "/classes/:class_name/edit", to: "classes#edit", via: :get, as: :edit_class
  # match "/classes/:class_name/update/", to: "classes#update", via: :patch, as: :update_class
  # match "/classes/new/", to: "classes#new", via: :get, as: :new_class
  # match "/classes/create/", to: "classes#create", via: :post, as: :create_class
  # match "/classes/:class_name/destroy/", to: "classes#destroy", via: :delete, as: :destroy_class
  # match "/classes/", to: "classes#index", via: :get, as: :classes

  resources :class_teachers, only: [:create, :destroy] do
    collection do
      delete ":id/destroy", to: "class_teachers#destroy", as: :destroy
    end
  end
  resources :classroom_teachers, only: [:create, :destroy] do
    collection do
      delete ":id/destroy", to: "classroom_teachers#destroy", as: :destroy
    end
  end

  # Lessons
  resources :lessons, only: [:destroy] do
    collection do
      match ":school_class_id/lessons", to: "lessons#new", via: :get, as: :new
      match ":school_class_id/create", to: "lessons#create", via: :post, as: :create
    end
  end

  resources :periods do
    collection do
      delete 'destroy_multiple'
    end
  end

  #Timetable
  # resources :time_table do
  #   collection do
  #     get 'view'
  #     get 'allocate_subjects'
  #   end
  # end

  get "/time_table", to: "time_table#index", as: :time_table
  get "/time_table/view", to: "time_table#view"
  get "/time_table/allocate_subjects", to: "time_table#allocate_subjects"
  get "/time_table/pdf/:class_name", to: "time_table#pdf_time_table", as: :pdf_time_table
  post "/time_table/:class_name/update/:period_id", to: "time_table#update", as: :update_time_table
  post "/time_table/:class_name/remove_subject/:period_id", to: "time_table#remove_subject", as: :remove_subject


  # Departments
  resources :departments

  # Courses
  resources :courses do
    collection do
      delete 'destroy_multiple'
    end
  end
  # match "courses/destroy/:id" => "courses#destroy", via: :delete, as: :destroy_course

  # Batches
  resources :batches do
    collection do
      delete 'destroy_multiple'
      get 'update_batches'
    end
  end
  
  # Admissions
  # get "admission" => "admission#index", as: :admissions
  get "/admission/new" => "admission#new", as: :new_admission
  post "/admission" => "admission#create"
  get "/admission/update_course"
  # get "/admission/show/:id" => "admission#show", :as => :admission_detail
  # get "/admission/edit/:id" => "admission#edit", :as => :admission_edit
  # delete "/admission/destroy/:id" => "admission#destroy", :as => :delete_admission
  # post "/admission/update/:id" => "admission#update", as: :update_admission

  # routes for school information
  get "general/settings", as: :school_edit
  match '/general/settings/update', to: 'school#update', :via => :post, as: :school_update

  ActiveAdmin.routes(self)
  # authenticated :user do
  #   root :to => "home#index"
  # end
  # unauthenticated :user do
  #   devise_scope :user do 
  #     get "/" => "devise/sessions#new"
  #   end
  # end

  devise_scope :user do
    match '/sessions/user', to: 'devise/sessions#create', via: :post
  end
  devise_for :users, :controllers => { :registrations => "registrations" } 
  resources :users
end


# For Production Enviroment
# if Rails.env.production?
#   devise_for :users, :controllers => { :registrations => "registrations" } 
# else
#   devise_for :users
# end

app/controllers/classes_controller.rb
class ClassesController < ApplicationController
	before_action :set_class, only: [:edit, :update, :destroy]
  before_filter :authenticate_user!

  def index
    @classes = SchoolClass.all
    add_breadcrumb "Classes"
    @class = SchoolClass.new
    @teachers = Employee.joins(:employee_position).where(
                :employee_positions => {:id => [2, 7]}
                ).order("employee_positions.name asc")

  end

  def new
    add_breadcrumb "Classes", classes_url
    add_breadcrumb "New Class"
    @class = SchoolClass.new
  end


  def show
    @class = SchoolClass.find_by_class_name(params[:class_name])
    @lesson = @class.lessons.build
    @class_subjects = @class.subjects
    @class_teachers = @class.teachers
    @class_students = @class.students
    add_breadcrumb "Classes", classes_url
    add_breadcrumb "Details"
  end

  def class_details
    @class = SchoolClass.find(params[:id])
    @lesson = @class.lessons.build
    @class_subjects = @class.subjects
    @class_teachers = @class.teachers
    @class_students = @class.students
    respond_to do |format|
      format.js
    end
  end

  def class_details_for_periods
    @class = SchoolClass.find(params[:id])
    @lesson = @class.lessons.build
    @week_days = WeekDay.all
    @periods = Period.all
    respond_to do |format|
      format.js
    end
  end

  def edit
    add_breadcrumb "Classes", classes_url
    add_breadcrumb "Edit Class"
  end

  # POST /batches
  # POST /batches.json
  def create
    @classes = SchoolClass.all
    @class = SchoolClass.new(class_params)
    add_breadcrumb "School Classes", classes_url
    add_breadcrumb "New Class"
    # respond_to do |format|
    if @class.save
      respond_to do |format|
        format.html { redirect_to classes_url }
        flash[:notice] = "Class was successfully created."
        format.json { head :no_content }
        format.js   { render :layout => false }
      end
      # format.html { redirect_to classes_url, notice: 'School Class was successfully created.' }
      # format.json { render :show, status: :created, location: @class }
    else
      respond_to do |format|
        format.html { render :new }
        flash[:alert] = @class.errors.full_messages.to_sentence
        # format.json { render json: @class.errors, status: :unprocessable_entity }
        format.json { head :no_content }
        format.js   { render :layout => false }
      end
      # end
    end
  end

  # PATCH/PUT /batches/1
  # PATCH/PUT /batches/1.json
  def update
    add_breadcrumb "Classes", classes_url
    add_breadcrumb "Edit"
    respond_to do |format|
      if @class.update(class_params)
        format.html { redirect_to classes_url, notice: 'Class was successfully updated.' }
        format.json { render :show, status: :ok, location: @class }
      else
        format.html { render :edit }
        flash[:alert] = @class.errors.full_messages.to_sentence
        format.json { render json: @class.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /batches/1
  # DELETE /batches/1.json
  def destroy
    @class.destroy
    respond_to do |format|
      format.html { redirect_to classes_url }
      flash.now[:notice] = "Class was successfully destroyed."
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end

  def destroy_multiple
    SchoolClass.destroy(params[:class_destroy_id])
    flash[:notice] = "Classes were successfully destroyed."
    respond_to do |format|
      format.html { redirect_to classes_url }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_class
      # begin
        @class = SchoolClass.find_by_class_name(params[:class_name])
      # rescue ActiveRecord::RecordNotFound
      #   redirect_to classes_url, :flash => { :error => "Record not found." }
      # end
    end

    def class_params
      params.require(:school_class).permit(:class_name, :short_name, :color)
    end
end

app/views/classes/_form.html.erb
<fieldset>
  <%= simple_form_for(@class, url: create_class_path, label_errors: true) do |f| %>
    <%#= f.error_notification %>
    <%= yield f %>
    <div class="row">
      <div class="col-md-6">
    
        <div class="form-inputs">
          <%= f.input :class_name, input_html: {class: "form-control"}, autofocus: true, placeholder: "Class Name" %>
        </div>


        <div class="form-inputs">
          <%= f.input :short_name, input_html: {class: "form-control"}, placeholder: "Short Name" %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-inputs">
          <%= f.input :color, as: :minicolors, input_html: {data: {
              minicolors: {theme: :bootstrap}}} %>
        </div>
      </div>
    </div>
    <div class="form-group"></div>

    <div class="form-actions">
      <%= f.submit "Create", class: "btn btn-primary" %>
      <%= link_to 'Cancel', classes_path, class: "btn btn-default", style: "color:#8B7C7C;" %>
    </div>
    
    <div class="form-group"></div>
      
  <% end %>
</fieldset>

app/views/classes/_list_classes.html.erb
<div class="">
    <div class="row">
      <div class="col-md-12">
        <div id="no-more-tables">
            <table class="table table-striped table-condensed cf">

              <thead class="cf">
                <tr>
                  <th class="col-md-2" data-title="Mark all">Mark All <input type="checkbox" id="select_all"/></th>
                  <th>Classes</th>
                  <th>Short Name</th>
                  <th>Color</th>
                  <th align="center" colspan="3">Actions</th>
                </tr>
              </thead>
              <tbody>
                <th class="for_responsive_table">Mark All <input type="checkbox" id="select_all"/></th>
                <% @classes.each do |_class| %>
                  <tr>
                    <td data-title="Mark" class="selectedId"><%= check_box_tag "class_destroy_id[]", _class.id %></td>
                    <td data-title="Classes"><%= _class.class_name %></td>
                    <td data-title="Short Name"><%= _class.short_name %></td>
                    <td data-title="Color">
                      <span style="padding: 4px 53px 4px 0px;background-color: <%=_class.color%>;"></span>
                    </td>
                    <td>
                      <%= link_to class_name_path(_class.class_name) do %>
                        <span class="glyphicon glyphicon-eye-open"></span>
                      <% end %> |
                      <%= link_to edit_class_path(_class.class_name) do %>
                        <span class="glyphicon glyphicon-edit"></span>
                      <% end %> |
                      <%= link_to destroy_class_path(_class.class_name), method: :delete, remote: true, data: { confirm: 'Are you sure?' }, class: "delete_class" do %>
                        <span class="glyphicon glyphicon-trash"></span>
                      <% end %>
                    </td>
                    
                  </tr>
                <% end %>
                <!-- <tr>
                  <td data-title="Code">AAD</td>
                  <td data-title="Company">ARDENT LEISURE GROUP</td>
                  <td data-title="Price" class="numeric">$1.15</td>
                  <td data-title="Change" class="numeric">+0.02</td>
                  <td data-title="Change %" class="numeric">1.32%</td>
                  <td data-title="Open" class="numeric">$1.14</td>
                  <td data-title="High" class="numeric">$1.15</td>
                  <td data-title="Low" class="numeric">$1.13</td>
                  <td data-title="Volume" class="numeric">56,431</td>
                </tr>
                <tr>
                  <td data-title="Code">AAX</td>
                  <td data-title="Company">AUSENCO LIMITED</td>
                  <td data-title="Price" class="numeric">$4.00</td>
                  <td data-title="Change" class="numeric">-0.04</td>
                  <td data-title="Change %" class="numeric">-0.99%</td>
                  <td data-title="Open" class="numeric">$4.01</td>
                  <td data-title="High" class="numeric">$4.05</td>
                  <td data-title="Low" class="numeric">$4.00</td>
                  <td data-title="Volume" class="numeric">90,641</td>
                </tr>
                <tr>
                  <td data-title="Code">ABC</td>
                  <td data-title="Company">ADELAIDE BRIGHTON LIMITED</td>
                  <td data-title="Price" class="numeric">$3.00</td>
                  <td data-title="Change" class="numeric">+0.06</td>
                  <td data-title="Change %" class="numeric">2.04%</td>
                  <td data-title="Open" class="numeric">$2.98</td>
                  <td data-title="High" class="numeric">$3.00</td>
                  <td data-title="Low" class="numeric">$2.96</td>
                  <td data-title="Volume" class="numeric">862,518</td>
                </tr>
                <tr>
                  <td data-title="Code">ABP</td>
                  <td data-title="Company">ABACUS PROPERTY GROUP</td>
                  <td data-title="Price" class="numeric">$1.91</td>
                  <td data-title="Change" class="numeric">0.00</td>
                  <td data-title="Change %" class="numeric">0.00%</td>
                  <td data-title="Open" class="numeric">$1.92</td>
                  <td data-title="High" class="numeric">$1.93</td>
                  <td data-title="Low" class="numeric">$1.90</td>
                  <td data-title="Volume" class="numeric">595,701</td>
                </tr>
                <tr>
                  <td data-title="Code">ABY</td>
                  <td data-title="Company">ADITYA BIRLA MINERALS LIMITED</td>
                  <td data-title="Price" class="numeric">$0.77</td>
                  <td data-title="Change" class="numeric">+0.02</td>
                  <td data-title="Change %" class="numeric">2.00%</td>
                  <td data-title="Open" class="numeric">$0.76</td>
                  <td data-title="High" class="numeric">$0.77</td>
                  <td data-title="Low" class="numeric">$0.76</td>
                  <td data-title="Volume" class="numeric">54,567</td>
                </tr>
                <tr>
                  <td data-title="Code">ACR</td>
                  <td data-title="Company">ACRUX LIMITED</td>
                  <td data-title="Price" class="numeric">$3.71</td>
                  <td data-title="Change" class="numeric">+0.01</td>
                  <td data-title="Change %" class="numeric">0.14%</td>
                  <td data-title="Open" class="numeric">$3.70</td>
                  <td data-title="High" class="numeric">$3.72</td>
                  <td data-title="Low" class="numeric">$3.68</td>
                  <td data-title="Volume" class="numeric">191,373</td>
                </tr>
                <tr>
                  <td data-title="Code">ADU</td>
                  <td data-title="Company">ADAMUS RESOURCES LIMITED</td>
                  <td data-title="Price" class="numeric">$0.72</td>
                  <td data-title="Change" class="numeric">0.00</td>
                  <td data-title="Change %" class="numeric">0.00%</td>
                  <td data-title="Open" class="numeric">$0.73</td>
                  <td data-title="High" class="numeric">$0.74</td>
                  <td data-title="Low" class="numeric">$0.72</td>
                  <td data-title="Volume" class="numeric">8,602,291</td>
                </tr>
                <tr>
                  <td data-title="Code">AGG</td>
                  <td data-title="Company">ANGLOGOLD ASHANTI LIMITED</td>
                  <td data-title="Price" class="numeric">$7.81</td>
                  <td data-title="Change" class="numeric">-0.22</td>
                  <td data-title="Change %" class="numeric">-2.74%</td>
                  <td data-title="Open" class="numeric">$7.82</td>
                  <td data-title="High" class="numeric">$7.82</td>
                  <td data-title="Low" class="numeric">$7.81</td>
                  <td data-title="Volume" class="numeric">148</td>
                </tr>
                <tr>
                  <td data-title="Code">AGK</td>
                  <td data-title="Company">AGL ENERGY LIMITED</td>
                  <td data-title="Price" class="numeric">$13.82</td>
                  <td data-title="Change" class="numeric">+0.02</td>
                  <td data-title="Change %" class="numeric">0.14%</td>
                  <td data-title="Open" class="numeric">$13.83</td>
                  <td data-title="High" class="numeric">$13.83</td>
                  <td data-title="Low" class="numeric">$13.67</td>
                  <td data-title="Volume" class="numeric">846,403</td>
                </tr>
                <tr>
                  <td data-title="Code">AGO</td>
                  <td data-title="Company">ATLAS IRON LIMITED</td>
                  <td data-title="Price" class="numeric">$3.17</td>
                  <td data-title="Change" class="numeric">-0.02</td>
                  <td data-title="Change %" class="numeric">-0.47%</td>
                  <td data-title="Open" class="numeric">$3.11</td>
                  <td data-title="High" class="numeric">$3.22</td>
                  <td data-title="Low" class="numeric">$3.10</td>
                  <td data-title="Volume" class="numeric">5,416,303</td>
                </tr> -->
              </tbody>
          </table>
        </div>
      </div>
    </div>
    
    <div class="row">
        <p class="bg-success" style="padding:10px;margin-top:20px"><small><a href="http://elvery.net/demo/responsive-tables/#no-more-tables" target="_blank">Link</a> to original article</small></p>
    </div>
</div>

app/views/classes/class_details.js.erb
$("#class_details_tab_1").html("<%= escape_javascript(render partial: '/classes/lessons/class_details') %>")

app/views/classes/class_details_for_periods.js.erb
$("#class_details_tab_2").html("<%= escape_javascript(render partial: '/classes/lessons/class_details_2') %>")
$('.tree li:has(ul)').addClass('parent_li').find(' > span').attr('title', 'Collapse this branch');
$('.tree li.parent_li > span').on('click', function (e) {
    var children = $(this).parent('li.parent_li').find(' > ul > li');
    if (children.is(":visible")) {
        children.hide('fast');
        $(this).attr('title', 'Expand this branch').find(' > i').addClass('icon-plus-sign').removeClass('icon-minus-sign');
    } else {
        children.show('fast');
        $(this).attr('title', 'Collapse this branch').find(' > i').addClass('icon-minus-sign').removeClass('icon-plus-sign');
    }
    e.stopPropagation();
});

app/views/classes/create.js.erb
<% if @class.save %>
	$('#new_school_class').bind('ajax:success', function() {
	    $("#notice").html("<%= escape_javascript(render :partial => 'layouts/messages' , :locals => { :flash => flash }).html_safe %>")
	    $("#list_of_classes").html("<%= escape_javascript(render :partial => 'list_classes') %>")
	    $(this).closest('form').find("input[type=text], textarea").val("");
	});
<% else %>
	$("#notice").html("<%= escape_javascript(render :partial => 'layouts/messages' , :locals => { :flash => flash }).html_safe %>")
<% end %> 

app/views/classes/destroy.js.erb
$('.delete_class').bind('ajax:success', function() {  
    $(this).closest('tr').fadeOut();
    $("#notice").html("<%= escape_javascript(render :partial => 'layouts/messages' , :locals => { :flash => flash }).html_safe %>")
}); 

app/views/classes/edit.html.erb
<fieldset>
  <%= simple_form_for(@class, url: update_class_path(@class.class_name), method: :patch, label_errors: true) do |f| %>
    <%#= f.error_notification %>
    <%= yield f %>
    <div class="row">
      <div class="col-md-6">
    
        <div class="form-inputs">
          <%= f.input :class_name, input_html: {class: "form-control"}, autofocus: true, placeholder: "Class Name" %>
        </div>


        <div class="form-inputs">
          <%= f.input :short_name, input_html: {class: "form-control"}, placeholder: "Short Name" %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-inputs">
          <%= f.input :color, as: :minicolors, input_html: {data: {
              minicolors: {theme: :bootstrap}}} %>
        </div>
      </div>
    </div>
    <div class="form-group"></div>

    <div class="form-actions">
      <%= f.submit "Update", class: "btn btn-primary" %>
    </div>
    
    <div class="form-group"></div>
      
  <% end %>
</fieldset>

app/views/classes/index.html.erb
<%= form_tag destroy_multiple_classes_path, method: :delete do %>
  <div class="row">
    <div class='col-md-12'>
      <div class="pull-left">
        <%= link_to 'Add Class', new_class_path, class: "btn btn-success" %>
      </div>
      <div class="pull-right">
        <%= button_tag "Delete selected", :remote => true, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-sm destroy-all pull-right", id: "my" %><br />
        <span id="select_notice" style="font-size:13px;" class="pull-right"></span>
      </div>
    </div>
  </div>
  <div class="row">
    <div class='col-md-12'>
      <h2>Classes</h2>
      <div id="list_of_classes">
        <% if @classes.present? %>
            <%= render :partial => 'list_classes' %>
        <% else %>
          <div class="alert alert-dismissable alert-info after-destroy" style="margin:0px !important; ">
            <strong>No Classes!</strong> Available.
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/classes/new.html.erb
<h3>Create new Class</h3>
<%= render partial: 'form' %>

app/views/classes/show.html.erb
<%#= link_to 'Edit', edit_class_path(@class), class: "label label-info" %>
<%= link_to 'Back', classes_path, class: "label label-default" %>
<br /><br />
<div class="row clearfix">
	<div class="col-md-12 column">
		<ul class="nav nav-tabs">
			<li >
				<a href="/" id="class_details_1" data-toggle="tooltip" data-placement="top" title="Details">Details</a>
				<%=hidden_field_tag "details_class", @class.id%>
			</li>
			<li>
				<a href="/" id="class_details_2" data-toggle="tooltip" data-placement="top" title="Assigned Lessons with Periods">Lessons</a>
				<%=hidden_field_tag "details_class_2", @class.id %>
			</li>
			<li>
				<a href="#">Add New Lesson</a>
			</li>
		</ul>
		
	</div>
</div>
<br />

<script src="src/easyTree.js"></script>
<div class="row">
	<div class="col-md-12" id="classes_all_details">
		<div id="class_details_tab_1">
			<%= render :partial => "/classes/lessons/class_details" %>
		</div>
		<div id="class_details_tab_2">
		</div>
		<div id="class_details_tab_3">
			<%= render :partial => "/classes/lessons/class_lesson_new" %>
		</div>
	</div>
</div>
<!-- <div class="col-md-4">
      <div class="panel panel-success">
        <%# s = WeekDay.all %>
        <%# q = @subject %>
        <%# s.map{|m| m.name } & q.periods.map{|m| m.week_day.name}  %>
        <div class="panel-heading periods">
          <h3 class="panel-title"><%#= week_day.name %></h3>
          <%#= link_to "Assign","#", :id => '#new_lesson_for_'+week_day.name, "data-toggle" => "modal", 'data-target' => '#new_lesson_'+week_day.name, class: "label label-success pull-right" %>
          <%#= render partial: "/lessons/new_lesson", locals: {:week_day => week_day} %>
        </div>
        <div class="panel-body">
          <div id="subject_lesson_<%#= week_day.id %>" class="for_periods">
            <%#= render partial: "/subjects/partials/lessons", locals: {:week_day => week_day} %>
          </div>
        </div>
      </div>
    </div> 
  
		<div class="panel panel-success">
			<div class="panel-heading">
				<h3 class="panel-title">
					Panel title
				</h3>
			</div>
			<div class="panel-body">
			</div>
			<div class="panel-footer">
			</div>
		</div>
	</div> -->