config/routes.rb
Rails.application.routes.draw do

  resources :school_classes
  resources :class_categories
  # School Classes
  # resources :classes
  match "/classes/class-:class_name/", to: "classes#show", via: :get, as: :class_name
  match "/classes/:class_name/edit", to: "classes#edit", via: :get, as: :edit_class
  match "/classes/:class_name/update/", to: "classes#update", via: :patch, as: :update_class
  match "/classes/new/", to: "classes#new", via: :get, as: :new_class
  match "/classes/create/", to: "classes#create", via: :post, as: :create_class
  match "/classes/:class_name/destroy/", to: "classes#destroy", via: :delete, as: :destroy_class
  match "/classes/", to: "classes#index", via: :get, as: :classes
  match "classes/:id/class_details/", to: "classes#class_details", via: :get, as: :class_details
  match "classes/:id/class_details_for_periods/", to: "classes#class_details_for_periods", via: :get, as: :class_details_for_periods
  match "classes/destroy_multiple/", to: "classes#destroy_multiple", via: :delete, as: :destroy_multiple_classes

  resources :classrooms do
    collection do
      delete 'destroy_multiple'
    end
  end


  resources :sessions

  # Fees Criteria
  resources :fees_particulars, only: [:destroy, :edit, :update, :show] do
    collection do
      post "types"
      get "update_students"
    end
  end
  resources :fees_categories do
    collection do
      get "fees_index"
    end
  end
  resources :fees_periods do
    collection do
      get "update_fees_particulars"
    end
  end

  get "home/bootstrap_form_test"

  match 'fees_particulars/new/:id' => 'fees_particulars#new', :via => :get, as: :new_fees_particulars
  match 'fees_particulars/create/:id' => 'fees_particulars#create', :via => :post, as: :create_fees_particulars
  match 'fees_particulars/update/:id' => 'fees_particulars#update', :via => :post, as: :update_fees_particulars
  # get 'home/index'
  root :to => "home#index"

  # match "/settings/" => 'home#settings', :as => :settings

  # Test logs with Redis
  # match "/log/" => 'home#log', :via => [:post]
  # match "/logEvent/" => 'home#log_event', :via => [:post]
  # match "/logException/" => 'home#log_exception', :via => [:post]
  # # match "/events/" => 'home#events', :via => [:get]
  # match "/redis/" => 'home#redis', :via => [:get], :as => :redis


  # Students Criteria
  resources :students do
    collection do
      post "remove_avatar/:id", to: "students#remove_avatar", as: :delete_avatar
      get "admissions"
      delete 'destroy_multiple'
    end
  end
  
  # Subjects Criteria
  resources :subject_allocations do
    collection do
      delete 'destroy_multiple'
      get "update_course"
      get "update_batch"
      get "update_department"
    end
  end
  resources :subjects do
    collection do
      get "update_course"
      get "list"
      delete 'destroy_multiple'
      get "update_course_for_search"
    end
  end
  resources :student_categories

  # Visitors
  # get "visitors/contact_us", to: "visitors#contact_us"
  # get "visitors/about_us", to: "visitors#about_us"
  

  # Employee Attendance
  resources :employee_attendance, only: [:employee_attendance_details] do
    collection do
      get "employee_attendance_details"
    end
  end

  # Employees
  resources :employee_positions
  resources :employees do
    collection do
      post "remove_avatar/:id", to: "employees#remove_avatar", as: :delete_avatar
      get "human_resources"
      delete 'destroy_multiple'
      # get ":employee_position_id/new", to: "employees#teacher_new", as: :new_teacher
      # post ":employee_position_id/create", to: "employees#teacher_create", as: :create_teacher
      get ":id/classes", to: "employees#classes", as: :teacher_class
    end
  end

  # Teachers
  get "/teachers", to: "teachers#index", as: :teachers
  get "/teachers/new", to: "teachers#new", as: :new_teacher
  post "/teachers/create", to: "teachers#create", as: :create_teacher
  get "/teachers/:id/edit", to: "teachers#edit", as: :edit_teacher
  post "/teachers/:id/update", to: "teachers#update", as: :update_teacher
  get "/teachers/:id", to: "teachers#show", as: :teacher
  delete "/teachers/:id/destroy", to: "teachers#destroy", as: :teacher_destroy
  delete "teachers/destroy_multiple/", to: "teachers#destroy_multiple", as: :destroy_multiple_teachers
  post "teacher/:id/remove_avatar", to: "teachers#remove_avatar", as: :delete_avatar_teacher
  # match "/classes/:class_name/edit", to: "classes#edit", via: :get, as: :edit_class
  # match "/classes/:class_name/update/", to: "classes#update", via: :patch, as: :update_class
  # match "/classes/new/", to: "classes#new", via: :get, as: :new_class
  # match "/classes/create/", to: "classes#create", via: :post, as: :create_class
  # match "/classes/:class_name/destroy/", to: "classes#destroy", via: :delete, as: :destroy_class
  # match "/classes/", to: "classes#index", via: :get, as: :classes

  resources :class_teachers, only: [:create, :destroy] do
    collection do
      delete ":id/destroy", to: "class_teachers#destroy", as: :destroy
    end
  end
  resources :classroom_teachers, only: [:create, :destroy] do
    collection do
      delete ":id/destroy", to: "classroom_teachers#destroy", as: :destroy
    end
  end

  # Lessons
  resources :lessons, only: [:destroy] do
    collection do
      match ":school_class_id/lessons", to: "lessons#new", via: :get, as: :new
      match ":school_class_id/create", to: "lessons#create", via: :post, as: :create
    end
  end

  resources :periods do
    collection do
      delete 'destroy_multiple'
    end
  end

  #Timetable
  # resources :time_table do
  #   collection do
  #     get 'view'
  #     get 'allocate_subjects'
  #   end
  # end

  get "/time_table", to: "time_table#index", as: :time_table
  get "/time_table/view", to: "time_table#view"
  get "/time_table/allocate_subjects", to: "time_table#allocate_subjects"
  get "/time_table/pdf/:class_name", to: "time_table#pdf_time_table", as: :pdf_time_table
  post "/time_table/:class_name/update/:period_id", to: "time_table#update", as: :update_time_table
  post "/time_table/:class_name/remove_subject/:period_id", to: "time_table#remove_subject", as: :remove_subject


  # Departments
  resources :departments

  # Courses
  resources :courses do
    collection do
      delete 'destroy_multiple'
    end
  end
  # match "courses/destroy/:id" => "courses#destroy", via: :delete, as: :destroy_course

  # Batches
  resources :batches do
    collection do
      delete 'destroy_multiple'
      get 'update_batches'
    end
  end
  
  # Admissions
  # get "admission" => "admission#index", as: :admissions
  get "/admission/new" => "admission#new", as: :new_admission
  post "/admission" => "admission#create"
  get "/admission/update_course"
  # get "/admission/show/:id" => "admission#show", :as => :admission_detail
  # get "/admission/edit/:id" => "admission#edit", :as => :admission_edit
  # delete "/admission/destroy/:id" => "admission#destroy", :as => :delete_admission
  # post "/admission/update/:id" => "admission#update", as: :update_admission

  # routes for school information
  get "general/settings", as: :school_edit
  match '/general/settings/update', to: 'school#update', :via => :post, as: :school_update

  ActiveAdmin.routes(self)
  # authenticated :user do
  #   root :to => "home#index"
  # end
  # unauthenticated :user do
  #   devise_scope :user do 
  #     get "/" => "devise/sessions#new"
  #   end
  # end

  devise_scope :user do
    match '/sessions/user', to: 'devise/sessions#create', via: :post
  end
  devise_for :users, :controllers => { :registrations => "registrations" } 
  resources :users
end


# For Production Enviroment
# if Rails.env.production?
#   devise_for :users, :controllers => { :registrations => "registrations" } 
# else
#   devise_for :users
# end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
	before_filter :authenticate_user!
  before_filter :set_teacher, only: [:show, :edit, :update, :destroy, :remove_avatar]

	def index
		add_breadcrumb "Teachers"
		@teacher_position = EmployeePosition.find_by_name("Teacher")
		@teachers = Employee.teachers
	end

	def new
		add_breadcrumb "Teachers", teachers_url
    add_breadcrumb "New Teacher"
    @teacher = Employee.teachers_position
    @teacher.educations.build
    @teacher.experiences.build
    
	end

	def edit
		add_breadcrumb "Teachers", teachers_url
    add_breadcrumb "Edit Teacher"
	end

	def show
		add_breadcrumb "Teachers", teachers_url
	end

	def create
    add_breadcrumb "Teachers", teachers_url
    add_breadcrumb "New Teacher"
    @teacher = Employee.teachers_position(teacher_params)
    if @teacher
      flash[:notice] = "Teacher Created Successfully"
      redirect_to teachers_path
    else
      flash[:alert] = @teacher.errors.full_messages.to_sentence
      render action: 'new'
    end
  end

	def update
		add_breadcrumb "Teachers", teachers_url
    add_breadcrumb "Edit Teacher"
    @teacher.update_attributes(teacher_params)
    if @teacher.save
      flash[:notice] = "Teacher was Updated Successfully"
      redirect_to teacher_path(@teacher)
    else
      flash[:notice] = @teacher.errors.full_messages.to_sentence
      render action: 'edit'
    end
	end

	def destroy
		@teacher.destroy
		respond_to do |format|
      format.html { redirect_to teachers_path }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
	end

	def destroy_multiple
    Employee.destroy(params[:teacher_destroy_id])
    flash[:notice] = "Teachers were successfully destroyed."
    respond_to do |format|
      format.html { redirect_to teachers_path }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end

	def remove_avatar
    @teacher.avatar = nil
    @teacher.save
    redirect_to @teacher
  end

	private

	def set_teacher
		begin
      @teacher = Employee.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to teachers_url, :flash => { :error => "Request Page not found." }
    end
	end

	def teacher_params
		params.require(:employee).permit(:first_name, :last_name, :date_of_birth, :gender, :employee_number,
                                     :joining_date, :job_title, :qualification, :total_experience, :present_address,
                                     :perminent_address, :phone, :email, :department_id, :avatar, :employee_position_id,
                                     :educations_attributes => [:id, :degree, :start_date, :completion_date, :institute_name,
                                      :still_attending, :_destroy],
                                     :experiences_attributes => [:id, :company, :position, :to_date, 
                                      :from_date, :still_attending, :_destroy]
                                     )
	end
end

app/views/teachers/_form.html.erb
<%= simple_form_for @teacher, url: create_teacher_path, method: :post, label_errors: true, class: "form-horizontal", :html => {:multipart => true} do |f| %>
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default bootstrap-admin-no-table-panel">
        <div class="panel-heading">
            <h4><strong>Create New Teacher</strong></h4>
        </div>
        <div class="bootstrap-admin-no-table-panel-content bootstrap-admin-panel-content collapse in">
          <div id="rootwizard">
            <% unless mobile_devise? %>
              <div class="navbar wizard_navbar" style="">
                <ul class="nav nav-pills wizard_nav">
                  <li><a href="#tab1" data-toggle="tab" enabled="false">Bio</a></li>
                  <li><a href="#tab2" data-toggle="tab">Address</a></li>
                  <li><a href="#tab3" data-toggle="tab">Employee Information</a></li>
                  <li><a href="#tab4" data-toggle="tab">Qualification</a></li>
                  <li><a href="#tab5" data-toggle="tab">Experience</a></li>
                  <li><a href="#tab6" data-toggle="tab">Avatar</a></li>
                </ul>
              </div>
            <% else %>
              <div class="navbar" style="">
                <ul class="nav nav-pills wizard_nav nav-stacked">
                  <li><a href="#tab1" data-toggle="tab" enabled="false">Bio</a></li>
                  <li><a href="#tab2" data-toggle="tab">Address</a></li>
                  <li><a href="#tab3" data-toggle="tab">Employee Information</a></li>
                  <li><a href="#tab4" data-toggle="tab">Qualification</a></li>
                  <li><a href="#tab5" data-toggle="tab">Experience</a></li>
                  <li><a href="#tab6" data-toggle="tab">Avatar</a></li>
                </ul>
              </div>
            <% end %>
            <div id="bar" class="progress  progress-striped active">
                <div class="progress-bar progress-bar-success" role="progressbar" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            <div class="tab-content">
              <div class="tab-pane" id="tab1">
                <h3>Bio:</h3>
                <fieldset>
                  <div class="row">
                    <div class="col-sm-6">
                      
                      <div class="form-inputs">
                        <span class="validate_first_name" style="color:#000;"></span>
                        <%= f.input :first_name, input_html:{class: "form-control"}, autofocus: true, placeholder: "First Name" %>
                      </div>
                      
                      <div class="form-inputs">
                        <span class="validate_last_name" style="color:#000;"></span>
                        <%= f.input :last_name, input_html:{class: "form-control"}, placeholder: "Last Name" %>
                      </div>
                    </div>
                    <div class="col-sm-6">
                      <div class="form-inputs">
                        <span class="validate_date_of_birth" style="color:#000;"></span>
                        <%= f.input :date_of_birth, input_html: {class: "form-control", :data => {'date-format' => 'YYYY/MM/DD'}}, placeholder: "Date of Birth", :as => :string %>
                      </div>
                      <div class="form-inputs">
                        <span class="validate_gender" style="color:#000;"></span>
                        <%= f.input :gender, collection: Employee::GENDER, as: :select, prompt: "Choose your Gender" %>
                      </div>
                    </div>
                  </div>
                </fieldset>
              </div>
              <div class="tab-pane" id="tab2">
                <h3>Address:</h3>
                <fieldset>
                  <div class="row">
                    <div class="col-sm-6">
                      <div class="form-inputs">
                        <span class="validate_present_address" style="color:#000;"></span>
                        <%= f.input :present_address, input_html: {class: "form-control"}, placeholder: "Current Address" %>
                      </div>

                      <div class="form-inputs">
                        <%= f.input :perminent_address, input_html: {class: "form-control"}, placeholder: "Permenent Address" %>
                      </div>
                    </div>
                    <div class="col-sm-6">
                      <div class="form-inputs">
                        <span class="validate_phone" style="color:#000;"></span>
                        <%=  f.input :phone, input_html: {class: "form-control"}, placeholder: "Contact Number" %>
                      </div>

                      <div class="form-inputs">
                        <span class="validate_email" style="color:#000;"></span>
                        <%= f.input :email, input_html: {class: "form-control"}, placeholder: "Email Address" %>
                      </div>
                    </div>
                  </div>
                </fieldset>
              </div>
              <div class="tab-pane" id="tab3">
                <h3>Teacher Details:</h3>
                <fieldset>
                  <div class="row">
                    <div class="col-sm-6">
                      <div class="form-inputs">
                        <span class="validate_employee_number" style="color:#000;"></span>
                        <%= f.input :employee_number, input_html: {class: "form-control"}, placeholder: "Employee Number", as: :integer %>
                      </div>

                      <div class="form-inputs">
                        <%#= f.label :joining_date, required: true %>
                        <%= f.input :joining_date, input_html: {class: "form-control", :data => {'date-format' => 'YYYY/MM/DD'}}, placeholder: "Joining Date", :as => :string %>
                      </div>
                    </div>
                    <div class="col-sm-6">
                      <!-- <div class="form-inputs">
                        <span class="validate_department" style="color:#000;"></span>
                        <%#= f.select :department_id, Department.all.map{|m| [m.name, m.id]}, class: "form-control", autofocus: true, prompt: "Choose a Department", hide_label: :true %>
                      </div> -->
                      <div class="form-inputs">
                        <span class="validate_job_title" style="color:#000;"></span>
                        <%= f.input :job_title, input_html: {class: "form-control"}, placeholder: "Job Title" %>
                      </div>
                    </div>
                  </div>
                </fieldset>
              </div>
              <div class="tab-pane" id="tab4">
                <h3>Qualification:</h3>
                  <div class="form-inputs">
                    <%= f.simple_fields_for :educations  do |builder| %>
                      <%= render "education_fields",  :f => builder %>
                      <%= link_to_add_association f, :educations, class: "btn btn-success pull-right" do %>
                        <i class="glyphicon glyphicon-plus"></i>Add Fields
                      <% end %>
                    <% end %>
                    <%#= link_to_add_fields_assocaitions 'Add Fields', f, :educations %>
                    
                    <br /><br />
                  </div>
              </div>
              <div class="tab-pane" id="tab5">
                <h3>Experience:</h3>
                <div class="form-inputs">

                  <%= f.simple_fields_for :experiences  do |builder| %> 
                      <%= render "experience_fields",  :f => builder  %>
                      <%= link_to_add_association f, :experiences, class: "btn btn-success pull-right" do %>
                        <i class="glyphicon glyphicon-plus"></i>Add Fields
                      <% end %>
                  <% end %>
                  <%#= link_to_add_fields_assocaitions 'Add Fields', f, :experiences %>
                  <br /><br />
                </div>
              </div>
              <div class="tab-pane" id="tab6">
                <h3>Profile Avatar</h3>
                <fieldset>
                  <div class="row">
                    <div class="col-sm-6">
                      <%= render :partial => 'teacher_avatar', locals: {:f => f} %>
                    </div>
                  </div>
                </fieldset>
              </div>
              <ul class="pager wizard">
                  <li class="previous first" style="display:none;"><a href="javascript:void(0);">First</a></li>
                  <li class="previous"><a href="javascript:void(0);">Previous</a></li>
                  <!-- <li class="next last" style="display:none;"><a href="javascript:void(0);">Last</a></li> -->
                  <li class="next"><a href="javascript:void(0);">Next</a></li>
                  <!-- <li class="next finish" style="display:none;"><a href="javascript:;">Finish</a></li> -->
                  <li class="next finish" style="display:none;">
                  <%#= link_to 'Submit', "", :onclick => "$('#new_employee').submit()" %><%= f.submit "Submit", class: "btn btn-primary pull-right" %>
                  </li>
                  
              </ul>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
<!-- <script type="text/javascript" src="/assets/jquery.bootstrap.wizard.js"></script>
<script type="text/javascript" src="/assets/jquery.bootstrap.wizard.min.js"></script> -->
<script type="text/javascript">
  $(function(){
    var $validator = $("#new_employee").validate({
      rules: {
        'employee[first_name]': {
          required: true
        },
        'employee[last_name]': {
          required: true
        },
        'employee[date_of_birth]': {
          required: true
        },
        'employee[gender]': {
          required: true
        },
        'employee[present_address]': {
          required: true
        },
        'employee[phone]': {
          required: true
        },
        'employee[email]': {
          required: true
        },
        'employee[employee_number]': {
          required: true
        },
        'employee[joining_date]': {
          required: true
        },
        'employee[department_id]': {
          required: true
        },
        'employee[educations_attributes][0][institute_name]': {
          required: true
        },
        'employee[educations_attributes][0][degree]': {
          required: true
        },
        'employee[educations_attributes][0][start_date]': {
          required: true
        },
        'employee[educations_attributes][0][completion_date]': {
          required: true
        },
        'employee[educations_attributes][0][still_attending]': {
          required: true
        },
        'employee[experiences_attributes][0][company]': {
          required: true
        },
        'employee[experiences_attributes][0][position]': {
          required: true
        },
        'employee[experiences_attributes][0][from_date]': {
          required: true
        },
        'employee[experiences_attributes][0][to_date]': {
          required: true
        }
        ,
        'employee[experiences_attributes][0][still_attending]': {
          required: true
        }

        // ,
        // 'employee[qualification]': {
        //   required: true
        // },
        // 'employee[total_experience]': {
        //   required: true
        // }
      }
    });
    $('#rootwizard').bootstrapWizard({
        'nextSelector': '.next',
        'previousSelector': '.previous',
        onNext: function(tab, navigation, index) {

            var $valid = $("#new_employee").valid();
            if(!$valid) {
              $validator.focusInvalid();
              return false;
            }
            var $total = navigation.find('li').length;
            var $current = index + 1;
            var $percent = ($current / $total) * 100;
            $('#rootwizard').find('.progress-bar').css('width', $percent + '%');
            // If it's the last tab then hide the last button and show the finish instead
            if ($current >= $total) {
                $('#rootwizard').find('.pager .next').hide();
                $('#rootwizard').find('.pager .finish').show();
                $('#rootwizard').find('.pager .finish').removeClass('disabled');
            } else {
                $('#rootwizard').find('.pager .next').show();
                $('#rootwizard').find('.pager .finish').hide();
            }

        },
        onPrevious: function(tab, navigation, index) {
            var $total = navigation.find('li').length;
            var $current = index + 1;
            var $percent = ($current / $total) * 100;
            $('#rootwizard').find('.progress-bar').css('width', $percent + '%');
            // If it's the last tab then hide the last button and show the finish instead
            if ($current >= $total) {
                $('#rootwizard').find('.pager .next').hide();
                $('#rootwizard').find('.pager .finish').show();
                $('#rootwizard').find('.pager .finish').removeClass('disabled');
            } else {
                $('#rootwizard').find('.pager .next').show();
                $('#rootwizard').find('.pager .finish').hide();
            }
        },
        onTabShow: function(tab, navigation, index) {
            var $total = navigation.find('li').length;
            var $current = index + 1;
            var $percent = ($current / $total) * 100;
            $('#rootwizard').find('.bar').css({width: $percent + '%'});
        }
    });
    // $('#rootwizard .finish').click(function() {
    //     alert('Finished!, Starting over!');
    //     $('#rootwizard').find('a[href*=\'tab1\']').trigger('click');
    // });
  });
</script>

app/views/teachers/_teacher_avatar.html.erb
<div class="form-group"></div>
  
<% if @teacher.present? %>
  <div class="fileinput fileinput-new" data-provides="fileinput">
    <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
      <% unless @teacher.avatar.present? %>
        <%= image_tag("school.png") %>
      <% else %>
        <%= image_tag @teacher.avatar.url %>
      <% end %>
    </div>
    <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>
    <div>
      <span class="btn btn-default btn-file"><span class="fileinput-new">Select image</span><span class="fileinput-exists">Change</span><%= file_field(:employee, :avatar) %></span>
      <% unless @teacher.avatar.present? %>
        <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
      <% else %>
        <% if file_field nil, :class => "fileinput-exists" %>
          <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
        <% end %>
        <%= link_to "Remove Picture", delete_avatar_teacher_path, :method => :post, class: "btn btn-default", data: {confirm: "Are you sure?"} %>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="fileinput fileinput-new" data-provides="fileinput">
    <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
      <!-- <img data-src="holder.js/100%x100%" alt="..."> -->
      <%= image_tag("school.png") %>
    </div>
    <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>
    <div>
      <span class="btn btn-default btn-file"><span class="fileinput-new">Select image</span><span class="fileinput-exists">Change</span>
        <%= file_field(:employee, :avatar) %>
      </span>
      <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
    </div>
  </div>
<% end %>

app/views/teachers/destroy.js.erb
$('.delete_teacher').bind('ajax:success', function() {  
    $(this).closest('tr').fadeOut();
    $("#notice").html("<%= escape_javascript(render :partial => 'layouts/messages' , :locals => { :flash => flash }).html_safe %>")
}); 

app/views/teachers/index.html.erb
<h1>Teachers</h1>

<%= form_tag destroy_multiple_teachers_path, method: :delete do %>
  <div class="row">
    <div class="col-sm-12">
      <div class="pull-left">
        <%= link_to 'New Teacher', new_teacher_path, class: "btn btn-success", data: { no_turbolink: true } %>
      </div>
      <div class="pull-right">
        <%= button_tag "Delete selected", :remote => true, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-sm destroy-all pull-right", id: "my" %><br />
        <span id="select_notice" style="font-size:13px;" class="pull-right"></span>
      </div>
    </div>
  </div>

  <hr />  
  <style type="text/css">
    body { font-size: 140% }
 
    table.dataTable th,
    table.dataTable td {
        white-space: nowrap;
    }
  </style>
  <script type="text/javascript">
    $(document).ready(function() {
        
        <% if mobile_devise? %>
          $('#example').dataTable( {
            "oLanguage": {
              "oPaginate": {
                "sNext": ">",
                "sPrevious": "<"
              }
            }
          } );
          $(".out_responsive_table").html("");
        <% else %>
          $('#example').dataTable();
        <% end %>
    } );
  </script>
    <% if mobile_devise? %>
      <strong class="">Mark All <input type="checkbox" id="select_all_out"/></strong>
      <br />
    <% end %>
    <div id="no-more-tables">
      <table id="example" class="table table-striped table-hover dt-responsive table-condensed cf" cellspacing="0" width="100%">

        <thead class="cf">
            <tr>
              
              <th class="out_responsive_table col-md-1">Mark All <input type="checkbox" id="select_all"/></th>
              <th>Name</th>
              <th>Gender</th>
              <th>Job title</th>
              <th>Joining Date</th>
              <th></th>
            </tr>
        </thead>
      
        <tbody>

            <% @teachers.each do |teacher| %>
              <tr>
                <td class="selectedId" data-title="Mark"><%= check_box_tag "teacher_destroy_id[]", teacher.id %></td>
                <td data-title="First Name"><%= teacher.first_name %></td>
                <td data-title="Last Name"><%= teacher.gender %></td>
                <td data-title="Job Title"><%= teacher.job_title %></td>
                
                <td data-title="Joining Date"><%= teacher.joining_date.strftime("%d %b, %Y") %></td>
                <td>
                  <%= link_to teacher_path(teacher) do %>
                  <span class="glyphicon glyphicon-eye-open"></span>
                  <% end %> |
                  <%= link_to edit_teacher_path(teacher) do %>
                    <span class="glyphicon glyphicon-edit"></span>
                  <% end %> |
                  <%= link_to teacher_destroy_path(teacher), method: :delete, remote: true, data: { confirm: 'Are you sure?' }, class: "delete_teacher" do %>
                    <span class="glyphicon glyphicon-trash"></span>
                  <% end %>
                </td>
              </tr>
            <% end %>
            
        </tbody>
      </table>
    </div>
<% end %>

<script type="text/javascript">
  // $(function(){
  //   $('#wizard').smartWizard();
  // })
</script>
<!-- <link href="smart_wizard.css" rel="stylesheet" type="text/css">
<script type="text/javascript" src="jquery.smartWizard.js"></script> -->
<!-- <div id="wizard" class="swMain">
  <ul>
    <li><a href="#step-1">
          <label class="stepNumber">1</label>
          <span class="stepDesc">
             Step 1<br />
             <small>Step 1 description</small>
          </span>
      </a></li>
    <li><a href="#step-2">
          <label class="stepNumber">2</label>
          <span class="stepDesc">
             Step 2<br />
             <small>Step 2 description</small>
          </span>
      </a></li>
    <li><a href="#step-3">
          <label class="stepNumber">3</label>
          <span class="stepDesc">
             Step 3<br />
             <small>Step 3 description</small>
          </span>                   
       </a></li>
    <li><a href="#step-4">
          <label class="stepNumber">4</label>
          <span class="stepDesc">
             Step 4<br />
             <small>Step 4 description</small>
          </span>                   
      </a></li>
  </ul>
  <div id="step-1">   
      <h2 class="StepTitle">Step 1 Content</h2>
 
  </div>
  <div id="step-2">
      <h2 class="StepTitle">Step 2 Content</h2> 
      
  </div>                      
  <div id="step-3">
      <h2 class="StepTitle">Step 3 Title</h2>   
       
  </div>
  <div id="step-4">
      <h2 class="StepTitle">Step 4 Title</h2>   
                              
  </div>
</div> -->